spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

    show-sql: true

logging:
  level:
    ROOT: ERROR